version: '2'

networks:
  kafka-nw:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - kafka-nw
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka-nw
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9999:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      - kafka-nw